server {
    if ($host = www.austinjiang.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = austinjiang.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name austinjiang.com www.austinjiang.com;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name austinjiang.com www.austinjiang.com;
    ssl_certificate /etc/letsencrypt/live/austinjiang.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/austinjiang.com/privkey.pem; # managed by Certbot

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/austinjiang.com;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /404.html;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
}

server {
    listen 80;
    server_name _;
    root /var/www/default;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 443 ssl;
    server_name _;
    ssl_certificate /etc/letsencrypt/live/austinjiang.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/austinjiang.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/default;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
}
